CREATE TABLE MED_ACIMA_PRESSAO_ATM
(ID NUMBER, PRESSAO_ATM_MED NUMBER);

CREATE TABLE MAX_TEMP_HIST_Q1
(ID NUMBER, MAX_TEMP NUMBER);

CREATE TABLE MAX_TEMP_HIST_Q2
(ID NUMBER, MAX_TEMP NUMBER);

CREATE TABLE MAX_TEMP_HIST_Q3 (
ID NUMBER, MAX_TEMP NUMBER);

CREATE TABLE MAX_TEMP_HIST_Q4
(ID NUMBER, MAX_TEMP NUMBER);

INSERT INTO MED_ACIMA_PRESSAO_ATM (ID, PRESSAO_ATM_MED)
SELECT id, pressao_atm
FROM temperaturas_marte
WHERE pressao_atm > 839;

INSERT INTO MAX_TEMP_HIST_Q1 (ID, MAX_TEMP)
SELECT id, max_temp
FROM temperaturas_marte
WHERE EXTRACT(MONTH FROM data_terra) BETWEEN 1 AND 3;

INSERT INTO MAX_TEMP_HIST_Q2 (ID, MAX_TEMP)
SELECT id, max_temp
FROM temperaturas_marte
WHERE EXTRACT(MONTH FROM data_terra) BETWEEN 4 AND 6;

INSERT INTO MAX_TEMP_HIST_Q3 (ID, MAX_TEMP)
SELECT id, max_temp
FROM temperaturas_marte
WHERE EXTRACT(MONTH FROM data_terra) BETWEEN 7 AND 9;

INSERT INTO MAX_TEMP_HIST_Q4 (ID, MAX_TEMP)
SELECT id, max_temp
FROM temperaturas_marte
WHERE EXTRACT(MONTH FROM data_terra) BETWEEN 10 AND 12;

SELECT 'MED_ACIMA_PRESSAO_ATM' AS TABELA, COUNT(*) AS QTD FROM MED_ACIMA_PRESSAO_ATM
UNION ALL
SELECT 'MAX_TEMP_HIST_Q1', COUNT(*) FROM MAX_TEMP_HIST_Q1
UNION ALL
SELECT 'MAX_TEMP_HIST_Q2', COUNT(*) FROM MAX_TEMP_HIST_Q2
UNION ALL
SELECT 'MAX_TEMP_HIST_Q3', COUNT(*) FROM MAX_TEMP_HIST_Q3
UNION ALL
SELECT 'MAX_TEMP_HIST_Q4', COUNT(*) FROM MAX_TEMP_HIST_Q4;

